language: rust
rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

env:
  - RUSTFLAGS='-D warnings'

before_script:
  # Download dependency repositories
  - .travis/download.sh deepwell
  - .travis/download.sh deepwell-rpc
  - .travis/download.sh ftml-rpc
  - .travis/download.sh ftml
  # Add rustfmt
  - rustup component add rustfmt
  # Add clippy
  - .travis/clippy.sh setup

script:
  # Ensure code is rustfmt'd
  - .travis/banner.sh rustfmt
  - rustfmt --edition=2018 src/main.rs --check
  # Check clippy lints
  - .travis/banner.sh clippy
  - .travis/clippy.sh check
  # Run build
  - .travis/banner.sh build
  - cargo build --release
  - cargo test --release -- --nocapture
  # Build documentation
  - .travis/banner.sh docs
  - cargo doc --no-deps

jobs:
  allow_failures:
    - rust: nightly
    - os: windows
  fast_finish: true

notifications:
  email:
    on_success: change
    on_failure: always
